name: BOTC-Plugin
author: Léo Ducruet
version: '1.0-SNAPSHOT'
main: net.ducruetl.BOTCPlugin.BOTCPlugin
api-version: '1.21'
commands:
  nametags:
    description: Show or hide nametags
    usage: "Usage: /nametags <enable|disable>"
    permission: botc.nametags
    permission-message: "You do not have permission to use this command."
  botc:
    description: BOTC Commands
    usage: "Usage: /botc <add|reset> <room|seat>"
    permission: botc
    permission-message: "You do not have permission to use this command."

permissions:
  botc:
    description: Allows use of BOTC related commands
    default: op
  botc.nametags:
    description: Allows use of /nametags
    default: op
